In [ ]:
!python --version

Python 3.9.13


In [ ]:
x = 10
y = 20
print(x)

10


In [ ]:
print(y)

20


In [ ]:
z = x+y
print(z)

30


In [ ]:
z1 = z+10
print(z1)

40


In [ ]:
type(z1)

int

In [ ]:
print('b')

b


In [ ]:
a = "hello"
len(a)

5

In [ ]:
a[2]

'l'

In [ ]:
p = a+' world'
print(p)

hello world


In [ ]:
type(p)

str

In [ ]:
p[0:4]

'hell'

In [ ]:
print("memory address of a:", id(a))

memory address of a: 2699808164912


In [ ]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [ ]:
names= ["ram","shyam","bharat","raj"]
print(names[2])

bharat


In [ ]:
books= {"a": "abc", "b": "bca", "c": "cde", "d": "def"}
auth= "c"
print(books[auth], " is written by ",auth)

cde  is written by  c


In [ ]:
import numpy as np
from numpy import random
b= random.randint(10,100, size=5)
c= random.rand()
print(c)
d= random.rand(5,6)
print(d)
e=random.random((3,4))
print(e)

0.8887855097847915
[[0.07087293 0.9615213  0.42052908 0.94887167 0.83428643 0.74339596]
 [0.03414859 0.39941548 0.52346569 0.06990323 0.6960108  0.01741821]
 [0.42289413 0.10194431 0.79197964 0.76067183 0.71820678 0.95474195]
 [0.02104069 0.74475036 0.21730991 0.30693274 0.39802339 0.67850135]
 [0.52518973 0.06106232 0.64611298 0.42017054 0.46135191 0.80501842]]
[[0.77171468 0.55507122 0.28140281 0.40166965]
 [0.65102737 0.30684121 0.17384913 0.93875885]
 [0.57082481 0.31279139 0.13115177 0.18335631]]


SyntaxError: EOL while scanning string literal (305247785.py, line 2)

In [ ]:
def add_num(x,y):
    """"this is an addition function""""
    x= 10
    y= 20
    z= x+y
    return(z)

SyntaxError: EOL while scanning string literal (1546182182.py, line 2)

In [ ]:
print(3+2*2**2//3)

5


In [ ]:
a= 1
b= 2
print(a+b)

3


In [ ]:
x=1
if(x!=1):
    print('Hello')
else:
    print('Hi')
    print('Mike')

Hi
Mike


In [ ]:
for n in range(3):
    print(n+1)

1
2
3


In [ ]:
def g(n): 
    s=0
    for i in range(1, n+1):
        if n%i == 0:
               s = s+1
    return(s)
a= g(25)
b= g(24)
diff= a-b
print(diff)

-5


In [ ]:
5+8
10-7
4*5
20/5
20//5
8%3
3**4

81

In [ ]:
8/3

2.6666666666666665

In [ ]:
name= "riya"
age= 21
print("{} is {} years old." .format(name,age))

riya is 21 years old.


In [ ]:
a= "1"
b= "2"
print(a+b)

12


In [ ]:
def add(x,y):
    return x+y
num1 = float(input("Enter first number"))
num2 = float(input("Enter second number"))
result = num1+num2
print(result)

Enter first number10
Enter second number20
30.0


In [ ]:
#simple calculator
def add(x,y):
    return x+y

def subtract(x,y):
    return x-y

def multiply(x,y):
    return x*y

def divide(x,y):
    if y!=0:
        return x/y
    else:
        return "cannot divide by zero"

num1=float(input("Enter first number:"))
num2=float(input("Enter second number:"))
operator=input("Enter operator (+,-,*,/):")

if operator == '+':
    result=add(num1,num2)
elif operator == '-':
    result=subtract(num1,num2)
elif operator == '*':
    result=multiply(num1,num2)
elif operator == '/':
    result=divide(num1,num2)
else:
    result="Invalid operator"

print("Result is:", result)

Enter first number:20
Enter second number:5
Enter operator (+,-,*,/):/
Result is: 4.0


In [ ]:
#number is equal, less than or greater than
num1=int(input("Enter first number:"))
num2=int(input("Enter first number:"))

if(num1 == num2):
    print("Both the numbers are equal")
elif num1 < num2:
    print("Num1 is less than num2")
else:
    print("Num1 is greater than num2")

Enter first number:200
Enter first number:100
Num1 is greater than num2


In [ ]:
#reverse a number
num=int(input("Enter a number:"))
reversed_num=0

while num>0:
    digit=num%10
    reversed_num=reversed_num * 10 +digit
    num = num // 10
print("Reversed number is", reversed_num)

Enter a number:12345
Reversed number is 54321


In [ ]:
num=int(input("Enter a number:"))
str_num=str(num)
reversed_str = str

In [ ]:
#fibonacci sequence
terms = int(input("How many terms? "))

if terms <= 0:
    print("Enter a positive integer")
elif terms == 1:
    print("Fibonacci sequence:")
    print(0)
else:
    print("Fibonacci sequence:")
    a, b = 0, 1
    print(a)
    print(b)
    for i in range(2, terms):
        a, b = b, a + b
        print(b)


How many terms? 10
Fibonacci sequence:
0
1
1
2
3
5
8
13
21
34


In [ ]:
nterms = int(input("How many terms? "))
n1,n2=0,1
count=0

if nterms<=0:
    print("Not available")

elif nterms ==1:
    print("Fibonacci sequence", n1)
else:
    print("Fibonacci sequence:")
    while count < nterms:
        print(n1)
        nth=n1+n2
        n1=n2
        n2=nth
        count+=1

KeyboardInterrupt: Interrupted by user

How many terms? 10


In [ ]:
n = int(input("Enter a number "))
sum=0

for x in range(1,n+1):
    if x % 2 !=0:
        sum = sum + x
print("Sum =", sum)

Enter a number 10
Sum = 25


In [ ]:
# Take input from the user
num = int(input("Enter a number: "))

# Find the number of digits in the number
num_digits = len(str(num))

# Initialize sum to 0
sum_of_powers = 0

# Make a copy of the original number
temp = num

# Calculate the sum of each digit raised to the power of the number of digits
while temp > 0:
    digit = temp % 10
    sum_of_powers += digit ** num_digits
    temp //= 10

# Check if the sum of powers is equal to the original number
if sum_of_powers == num:
    print(f"The number {num} is an Armstrong number.")
else:
    print(f"The number {num} is not an Armstrong number.")

Enter a number: 145
The number 145 is not an Armstrong number.


In [ ]:
sum1=0
num = int(input("Enter a number: "))
temp = num 

while num:
    i=1
    f=1
    r =num % 10
    while i <=r:
        f=f*i
        i=i+1
    
    sum1=sum1 + f
    num = num // 10
    
if sum1 == temp:
    print("The number is a strong number")
else:
    print("The number is not a strong number")

Enter a number: 145
The number is a strong number


In [ ]:
import math

a = float(input("Enter the value of a: "))
b = float(input("Enter the value of b: "))
c = float(input("Enter the value of c: "))

if a == 0 and b == 0:
    print("No solution: a & b both cannot be zero.")
    exit()

if a == 0:
    x = -c / b
    print(f"Linear equation: root = {x:.3f}")
    exit()

D = b ** 2 - 4 * a * c

if D >= 0:
    root1 = (-b + math.sqrt(D)) / (2 * a)
    root2 = (-b - math.sqrt(D)) / (2 * a)
    print(f"The roots are real: {root1:.3f} and {root2:.3f}")
else:
    real_part = -b / (2 * a)
    imag_part = math.sqrt(abs(D)) / (2 * a)
    print(f"The roots are complex: {real_part:.3f}+{imag_part:.3f}i and {real_part:.3f}-{imag_part:.3f}i")


Enter the value of a:  1
Enter the value of b:  2
Enter the value of c:  4


The roots are complex: -1.000+1.732i and -1.000-1.732i


In [ ]:
def calculate_grade():
    num_subjects = int(input("Enter the number of subjects: "))
    total_marks = 0
    for i in range(num_subjects):
        marks = int(input(f"Enter marks for subject {i + 1}: "))
        if marks < 0 or marks > 100:
            print("Invalid marks entered! Marks should be between 0 and 100.")
            return
        total_marks += marks
    percentage = (total_marks / (num_subjects * 100)) * 100
    print(f"Total Marks: {total_marks}")
    print(f"Percentage: {percentage}%")
    if percentage >= 92:
        print("Merit")
    elif 75 <= percentage < 92:
        print("Distinction")
    elif 60 <= percentage < 75:
        print("First Class")
    elif 45 <= percentage < 60:
        print("Second Class")
    else:
        print("Fail")
 
calculate_grade()


Enter the number of subjects:  4
Enter marks for subject 1:  89
Enter marks for subject 2:  87
Enter marks for subject 3:  90
Enter marks for subject 4:  77


Total Marks: 343
Percentage: 85.75%
Distinction


In [ ]:
n = int(input("Enter the number of lines: "))

for i in range(n):
    # Print leading spaces
    print(" " * (2 * i), end="")

    for j in range(n - i, 0, -1):
        print(j, end=" ")

    print()



Enter the number of lines:  6


6 5 4 3 2 1 
  5 4 3 2 1 
    4 3 2 1 
      3 2 1 
        2 1 
          1 


In [ ]:
user_input = input("Enter a string: ")

string_length = len(user_input)

print(f"The length of the string is: {string_length}")

Enter a string: hello
The length of the string is: 5


In [ ]:
string = input("Enter a string: ")
for i in string:
    frequency = string.count(i)
    print(str(i) + ": " +str(frequency))

Enter a string: hello world
h: 1
e: 1
l: 3
l: 3
o: 2
 : 1
w: 1
o: 2
r: 1
l: 3
d: 1


In [ ]:
user_input = input("Enter a string: ")
if len(user_input) >=2:
    result = user_input[:2] + user_input[-2:]
else:
    result = " "
print(f"The result string is: {result}")

Enter a string: python
The result string is: pyon


In [ ]:
user_input = input("Enter a string: ")
if user_input:
    first_char = user_input[0]
    modified_string = first_char + user_input[1:].replace(first_char,'$')
    print(f"The modified string is: {modified_string}")
else:
    print("Please enter a string")

Enter a string: resource
The modified string is: resou$ce


In [ ]:
user_input = input("Enter a string: ")
for i in user_input

Enter a string: hello
The modified string is: hello


In [ ]:
main_string = input("Enter a main string: ")
substring = input("Enter the substring: ")

if substring in main_string:
    print(f"The substring '{substring}' is present in main string")
else:
    print(f"The substring '{substring}' is not present in main string")

Enter a main string: hello world 
Enter the substring: world
The substring 'world' is present in main string


In [ ]:
user_input = input("Enter a string: ")
if len(user_input) >=2:
    new_string = user_input[-1] + user_input[1:-1] + user_input[0]
    print("Original string:", user_input)
    print("New string:", new_string)
else:
    print("String must contain atleast two characters")

Enter a string: python
Original string: python
New string: nythop


In [ ]:
user_input = input("Enter a string: ")
lowercase_input = user_input.lower()

if lowercase_input == lowercase_input[::-1]:
    print("The string is palindrome")
else:
    print("The string is not palindrome")
print("Original String: ",user_input)
print("Reversed String: ",user_input[::-1])

Enter a string: radar
The string is palindrome
Original String:  radar
Reversed String:  radar


In [ ]:
string1 = input("Enter string 1: ")
string2 = input("Enter string 2: ")
result = ""

for char in string1 + string2:
    if char.isupper():
        result= result + char
print("The resultant string is:", result)

Enter string 1: Java Programming
Enter string 2: Python Programming
The resultant string is: JPPP


In [ ]:
string1 = input("Enter a string: ").lower()
string2 = input("Enter a string: ").lower()
string1_sorted = sorted(string1)
print(string1_sorted)
string2_sorted = sorted(string2)

if string1_sorted == string2_sorted:
    print("True")
else:
    print("False")

Enter a string: python
Enter a string: pythonnn
['h', 'n', 'o', 'p', 't', 'y']
False


In [ ]:
words = input("Enter the words separated by spaces and/or commas: \n")
words_list = words.split()
long_words = 0
total_words = 0
for word in words_list:
    if len(word) > 6:
        long_words +=1
    total_words +=1
percentage = (long_words/total_words) * 100
print(f"{percentage: .2f}% of words are more than 6 letters long")

Enter the words separated by spaces and/or commas: 
The name of my college is Mukesh Patel School of Technology
 18.18% of words are more than 6 letters long


In [ ]:
sentence=input("Enter a sentence: ")
words=sentence.split()
new_sentence=""

for i,word in enumerate(words):
    if i%2 == 0:
        new_sentence+= word + " "
    else:
        new_sentence+=word[::-1] + " "
print(new_sentence + ".")

Enter a sentence: this is a simple sentence
this si a elpmis sentence .


In [ ]:
string=input("Enter a sentence: ")
string=''.join(string.split())
print("Resultant string:",string)

Enter a sentence: this is     a     sentence
Resultant string: thisisasentence


In [ ]:
sentence = input("Enter a sentence: ")

characters = []
counts = []

for char in sentence:
    if char != ' ':
        if char in characters:
            index = characters.index(char)
            counts[index] += 1
        else:
            characters.append(char)
            counts.append(1)

for i in range(len(characters)):
    print(f"{characters[i]}: {'*' * counts[i]}")


Enter a sentence: this is my python programming code 
t: **
h: **
i: ***
s: **
m: ***
y: **
p: **
o: ***
n: **
r: **
g: **
a: *
c: *
d: *
e: *


In [ ]:
class Stack:
    def __init__(self):
        self.stack = []
    def push(self, item):
        self.stack.append(item)
    def pop(self):
        if not self.is_empty():
            return self.stack.pop()
        else:
            return "Stack is empty"
    def peek(self):
        if not self.is_empty():
            return self.stack[-1]
        else:
            return "Stack is empty"
    def is_empty(self):
        return len(self.stack) == 0
if __name__ == "__main__":
    stack=Stack()
    stack.push(10)
    stack.push(20)
    stack.push(30)
    print(f"Top item: {stack.peek()}")
    print(f"Popped item: {stack.pop()}")
    print(f"Popped item: {stack.pop()}")
    print(f"Is tack empty? {stack.is_empty()}")
    print(f"Popped item: {stack.pop()}")
    print(f"Is stack empty? {stack.is_empty()}")

Top item: 30
Popped item: 30
Popped item: 20
Is tack empty? False
Popped item: 10
Is stack empty? True


1.	Give new name to the user by exchanging first and last characters of his/her name



In [ ]:
username=input("Enter your name:")
new_name=username[-1] + user_name[1:-1] + user_name[0]
print("New Name:",new_name)

Enter your name:riya
New Name: aiyr


2. Teacher has entered math marks for all the students in a list. Help her to print the second highest and second lowest marks. Use list data structure.



In [ ]:
math_marks=[20,70,50,10,40,30]
sorted_marks=sorted(math_marks)
print(sorted_marks)

print("Second lowest marks:",sorted_marks[1])
print("Second highest marks:",sorted_marks[-2])

[10, 20, 30, 40, 50, 70]
Second lowest marks: 20
Second highest marks: 50


3.	Teacher has to select all the students having roll numbers, that are multiple of 5. Help the teacher. Use list data structure


In [ ]:
#with loop
roll_no=[10,13,20,50,45,80,7]
selected_students=[]
for roll_no in roll_no:
    if roll_no%5==0:
        selected_students.append(roll_no)
sorted_selected_students=sorted(selected_students)
print(sorted_selected_students)

[10, 20, 45, 50, 80]


In [ ]:
#with list comprehension
roll_no=[10,13,20,50,45,80,7]
selected_students=[roll for roll in roll_no if roll%5==0]
print("Students with roll number as multiples of 5:",selected_students)

Students with roll number as multiples of 5: [10, 20, 50, 45, 80]


4.	For a given number A which contains only digits 0's and 1's, if it is possible to make all digits same by flipping only one digit, print YES, else print NO


In [ ]:
num_a=input("Enter a no containing only 0's and 1's:")
count_0=num_a.count('0')
count_1=num_a.count('1')
result="Yes" if count_0==1 or count_1==1 else "No"
print(result)

Enter a no containing only 0's and 1's:1000
Yes


5. Student names are saved in a tuple. Find the length of each student name.

In [ ]:
student_names=('riya','prisha','helly','rashi')
name_length=[len(name) for name in student_names]
for i in range (len(student_names)):
    print(f"Length of {student_names[i]}: {name_length[i]}")

Length of riya: 4
Length of prisha: 6
Length of helly: 5
Length of rashi: 5


6. Take a paragraph from some book. Create a dictionary consisting of all the words and its frequency in the given text.



In [ ]:
paragraph="""In a hole in the ground there lived a hobbit. 
Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, 
sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort."""

import string
paragraph=paragraph.translate(str.maketrans("","",string.punctuation)).lower()
print(paragraph)

word_frequency={}
words=paragraph.split()
print(words)
for word in words:
    word_frequency[word] = word_frequency.get(word,0) + 1
    
print("Word Frequency Dictionary ")
for word,frequency in word_frequency.items():
    print(f"{word}: {frequency}")

in a hole in the ground there lived a hobbit 
not a nasty dirty wet hole filled with the ends of worms and an oozy smell nor yet a dry bare 
sandy hole with nothing in it to sit down on or to eat it was a hobbithole and that means comfort
['in', 'a', 'hole', 'in', 'the', 'ground', 'there', 'lived', 'a', 'hobbit', 'not', 'a', 'nasty', 'dirty', 'wet', 'hole', 'filled', 'with', 'the', 'ends', 'of', 'worms', 'and', 'an', 'oozy', 'smell', 'nor', 'yet', 'a', 'dry', 'bare', 'sandy', 'hole', 'with', 'nothing', 'in', 'it', 'to', 'sit', 'down', 'on', 'or', 'to', 'eat', 'it', 'was', 'a', 'hobbithole', 'and', 'that', 'means', 'comfort']
Word Frequency Dictionary 
in: 3
a: 5
hole: 3
the: 2
ground: 1
there: 1
lived: 1
hobbit: 1
not: 1
nasty: 1
dirty: 1
wet: 1
filled: 1
with: 2
ends: 1
of: 1
worms: 1
and: 2
an: 1
oozy: 1
smell: 1
nor: 1
yet: 1
dry: 1
bare: 1
sandy: 1
nothing: 1
it: 2
to: 2
sit: 1
down: 1
on: 1
or: 1
eat: 1
was: 1
hobbithole: 1
that: 1
means: 1
comfort: 1


7.Create a dictionary from following two lists. The first list will have name of the students and
second list will have their corresponding marks

In [ ]:
#use in zip
student_names = ["Riya","Diya","Helly","Misha"]
marks = [30,40,23,33]
result = {s:m for s,m in zip(student_names,marks)}
print(result)

{'Riya': 30, 'Diya': 40, 'Helly': 23, 'Misha': 33}


8. Implement Caesar Cipher using Python Dictionary:
 Caesar Cipher shift =3 means each letter will be replace by 3 letters a->d, e->h, b->e

In [ ]:
alphabet = 'abcdefghijklmnopqrstuvwxyz'
shift = 3
cipher_dict = {alphabet[i] : alphabet[(i+shift) % 26] for i in range(len(alphabet))}
plain_text="Hello"
cipher_text =''.join(cipher_dict.get(char,char) for char in plain_text.lower())
print("Plain text:",plain_text)
print("Cipher text:",cipher_text)

Plain text: Hello
Cipher text: khoor


9. Create set S1 will all even numbers from 1 to 100. Create set S2 with all squares of numbers 1 to 10. 
Create the following sets from these two sets
i . Union of S1 and S2
ii. Intersection of S1 and S2.

In [ ]:
S1 = {x for x in range(1, 101) if x % 2 == 0}
S2 = {x**2 for x in range(1, 11)}
union_set = S1 | S2
print("Union of S1 and S2:", union_set)
intersection_set = S1 & S2
print("Intersection of S1 and S2:", intersection_set)

Union of S1 and S2: {1, 2, 4, 6, 8, 9, 10, 12, 14, 16, 18, 20, 22, 24, 25, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 49, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 81, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100}
Intersection of S1 and S2: {64, 100, 4, 36, 16}


10. Create a list in python for storing supermarket bill details and perform the following operations on it:
● Add an item to the end of the list ● Insert an item at a given position ● Modify an element by using the index of the element ● Remove an item from the list ● Remove all items from the list ● Slice Elements from a List ● Remove the item at the given position in the list, and return it ● Return the number of times 'x' appear in the list ● Sort the items of the list in place ● Reverse the elements of the list in place

In [ ]:
supermarket_bill = []
supermarket_bill.append("bread")
supermarket_bill.append("milk")
supermarket_bill.append("cheese")

print("Bill after adding items:", supermarket_bill)

supermarket_bill.insert(1, "eggs")
print("Bill after inserting eggs:", supermarket_bill)

supermarket_bill[0] = "almond bread"
print("Bill after modifying item at index 0:", supermarket_bill)

supermarket_bill.remove("cheese")
print("Bill after removing cheese:", supermarket_bill)

supermarket_bill.clear()
print("Bill after removing all items:", supermarket_bill)

supermarket_bill = ["bread", "milk", "cheese", "eggs", "butter"]
sliced_bill = supermarket_bill[1:4]
print("Sliced bill (from index 1 to 3):", sliced_bill)

removed_item = supermarket_bill.pop(2)
print("Removed item at position 2:", removed_item)
print("Bill after removing item at position 2:", supermarket_bill)

count_milk = supermarket_bill.count("milk")
print("Number of times 'milk' appears in the bill:", count_milk)

supermarket_bill.sort()
print("Bill after sorting items:", supermarket_bill)

supermarket_bill.reverse()
print("Bill after reversing items:", supermarket_bill)


Bill after adding items: ['bread', 'milk', 'cheese']
Bill after inserting eggs: ['bread', 'eggs', 'milk', 'cheese']
Bill after modifying item at index 0: ['almond bread', 'eggs', 'milk', 'cheese']
Bill after removing cheese: ['almond bread', 'eggs', 'milk']
Bill after removing all items: []
Sliced bill (from index 1 to 3): ['milk', 'cheese', 'eggs']
Removed item at position 2: cheese
Bill after removing item at position 2: ['bread', 'milk', 'eggs', 'butter']
Number of times 'milk' appears in the bill: 1
Bill after sorting items: ['bread', 'butter', 'eggs', 'milk']
Bill after reversing items: ['milk', 'eggs', 'butter', 'bread']


11.  Write a python program to count positive and negative numbers in a list

In [ ]:
numbers = [1, -2, 3, -4, 5, -6]
positive = len([num for num in numbers if num > 0])
negative = len([num for num in numbers if num < 0])
print("Positive numbers:", positive)
print("Negative numbers:", negative)

Positive numbers: 3
Negative numbers: 3


 12. Write a python program to sum all the elements in a list.

In [ ]:
numbers = [1, 2, 3, 4, 5]
total_sum = sum(numbers)
print("Sum of all elements:", total_sum)

Sum of all elements: 15


13. Write a Python program to find the list of words that are longer than n from a given list of words.

In [ ]:
words_list = ["apple", "banana", "kiwi", "cherry", "fig"]
n = 4

long_words = [word for word in words_list if len(word) > n]
print("Words longer than", n, "characters:", long_words)

14. Write a Python program to find the list in a list of lists whose sum of elements is the highest.
Sample lists: [1,2,3], [4,5,6], [10,11,12], [7,8,9] Expected Output: [10, 11, 12]

In [ ]:
lists = [[1, 2, 3], [4, 5, 6], [10, 11, 12], [7, 8, 9]]

max_sum_list = max(lists, key=sum)
print("List with the highest sum:", max_sum_list)

List with the highest sum: [10, 11, 12]


In [ ]:
##################################################################################################################

In [ ]:
#1. What will be the output of following program?

numbers = [1, 2, 3, 4]
numbers.append([5,6,7,8])
#print(numbers)
print(len(numbers))
 # 4, 5, 8, 12
    #Output [1, 2, 3, 4, [5, 6, 7, 8]]

5


In [ ]:

#2.What will be displayed by the following code?
list1 = [1, 3]
list2 = list1
list1[0] = 4
print(list2)
 # [4,3], [1,3], [1,4], [1,2,3]

[4, 3]


In [ ]:
#3. What will be the output of the following code? Write your answer

str1="Investigator"
print(str1[2:8])

vestig


In [ ]:
#4. What will be the output of below Python code? Write your answer

"Programming".capitalize()

'Programming'

In [ ]:
#4. What will be the output of below Python code? Write your answer

"programming of python".capitalize()

'Programming of python'

In [ ]:
#5. What is the output of the following code?Write your answer.
My_tuple= (20,100,40,30)
My_tuple[1]= 75
Print(My_tuple)


TypeError: 'tuple' object does not support item assignment

In [ ]:
##################################################################################################################



#Q1. Select the correct way to print Emma’s age.
student = {1: {'name': 'Emma', 'age': '27', 'sex': 'Female'},
           2: {'name': 'Mike', 'age': '22', 'sex': 'Male'}}
student[0][1]
student[1]["age"]
student[0]["age"]

#ans is print(student[1]["age"])


In [ ]:
student = {1: {'name': 'Emma', 'age': '27', 'sex': 'Female'},
           2: {'name': 'Mike', 'age': '22', 'sex': 'Male'}}
print(student[1]["age"])

27


#Q2. What is the output of the following code
dict1 = {"key1":1, "key2":2}
dict2 = {"key2":2, "key1":1}
print(dict1 == dict2)
  #True or False
    
#True

In [ ]:
dict1 = {"key1":1, "key2":2}
dict2 = {"key2":2, "key1":1}
print(dict1 == dict2)

True


#Q3. Select all correct ways to copy a dictionary in Python


  dict2 = dict1.copy()
  dict2 = dict(dict1)
  dict2 = dict1
#dict2 = dict1.copy()


In [ ]:
dict1 = {"key1":1, "key2":2}
dict2 = {"key2":2, "key1":1}
print(dict1 == dict2)

dict2 = dict1.copy()
dict2 = dict(dict1)

True


#Q4. Select the correct way to access the value of a history subject
sampleDict = { 
   "class":{ 
      "student":{ 
         "name":"Mike",
         "marks":{ 
            "physics":70,
            "history":80
         }
      }
   }
}
  sampleDict['class']['student']['marks']['history']
  sampleDict['class']['student']['marks'][1]
  sampleDict['class'][0]['marks']['history']
  
  #sampleDict['class']['student']['marks']['history']

In [ ]:
sampleDict = { 
   "class":{ 
      "student":{ 
         "name":"Mike",
         "marks":{ 
            "physics":70,
            "history":80
         }
      }
   }
}
sampleDict['class']['student']['marks']['history']

80

#Q5. What is the output of the following?
sampleSet = {"Yellow", "Orange", "Black"}
sampleSet.discard("Blue")
print(sampleSet)
  {‘Yellow’, ‘Orange’, ‘Black’}
  KeyError: ‘Blue’

Indentation Error
OR
{'Yellow', 'Orange', 'Black'}

In [ ]:
sampleSet = {"Yellow", "Orange", "Black"}
sampleSet.discard("Blue")
print(sampleSet)


{'Yellow', 'Orange', 'Black'}


In [ ]:
def gcd(a,b):
    while b!=0:
        a, b = b, a % b
    return a
a=4
b=8
result = gcd(a, b)
print("The GCD of", a, "and", b, "is:", result)

The GCD of 4 and 8 is: 4


In [ ]:
def mul(num):
    return num * 3

def sub(num):
    return mul(num) - 2

result_mul=mul(5)
result_sub=sub(10)

print(f"Result of mul function: {result_mul}")
print(f"Result of sub function: {result_sub}")

Result of mul function: 15
Result of sub function: 28


In [ ]:
def student(name,standard="11th",school_name="St joseph"):
    print(f"Student Name: {name}")
    print(f"Standard: {standard}")
    print(f"School: {school_name}")
    
student("Riya")
student("Prisha","12th","St Xavier")

Student Name: Riya
Standard: 11th
School: St joseph
Student Name: Prisha
Standard: 12th
School: St Xavier


In [ ]:
import math
def square_root(num):
    return math.sqrt(num)
result=square_root(4)
print("Square root of 4 is:", result)

Square root of 4 is: 2.0


In [ ]:
furniture = ["sofa","table","dinig_table","tv_stand","cupboard"]
cost = [20000,8500,4599,13920]

def calculate_bill(furniture_name,quantity):
    if furniture_name not in furniture:
        print("Error: Furniture not available")
        return 0
    index = furniture.index(furniture_name)
    if quantity <=0:
        print("Error: Invalid quantity.")
        return 0
    bill = cost[index] * quantity
    return bill

furniture_name = input("Enter the furniture name:")
quantity = int(input("Enter the number of quantity:"))

bill = calculate_bill(furniture_name,quantity)
if bill!=0:
    print("The amount to be paid is", bill)

Enter the furniture name:sofa
Enter the number of quantity:4
The amount to be paid is 80000


In [ ]:
courses = ("Python Programming", "RDBMS", "Web Technology", "Software Engg.")
electives = ("Business Intelligence", "Big Data Analytics")

def list_course(courses):
    print(f"The number of courses opted by John: {len(courses)}")
    print(f"The courses opted by John: {courses}")

def add_electives(courses, electives):
    updated_courses = courses + electives
    return updated_courses

list_course(courses)

updated_courses = add_electives(courses, electives)

print("\nUpdated list of courses including electives:")
for course in updated_courses:
    print(course)


The number of courses opted by John: 4
The courses opted by John: ('Python Programming', 'RDBMS', 'Web Technology', 'Software Engg.')

Updated list of courses including electives:
Python Programming
RDBMS
Web Technology
Software Engg.
Business Intelligence
Big Data Analytics


In [ ]:
marks = {"John": 86.5, "Jack": 91.2, "Jill": 845.5, "Harry": 72.1, "Joe": 80.5}

def display_marks(marks):
    for name, mark in marks.items():  
        print("Name:", name, "Marks:", mark)
        
def display_top_scorers(marks):
    sorted_marks = sorted(marks.items(), key=lambda x: x[1], reverse=True)
    print("*********************************")
    print("Top two scorers:")
    for i in range(2):
        print("Name:", sorted_marks[i][0], "Marks:", sorted_marks[i][1])

def display_average(marks):
    total = sum(marks.values())
    average = total / len(marks)
    print("*********************************")
    print(f"Class Average: {average:.2f}")

display_marks(marks)
display_top_scorers(marks)
display_average(marks)


Name: John Marks: 86.5
Name: Jack Marks: 91.2
Name: Jill Marks: 845.5
Name: Harry Marks: 72.1
Name: Joe Marks: 80.5
*********************************
Top two scorers:
Name: Jill Marks: 845.5
Name: Jack Marks: 91.2
*********************************
Class Average: 235.16


In [ ]:
java_course = {"John", "Jack", "Jill", "Joe"}
python_course = {"Jake", "John", "Eric", "Jill"}
 
python_count = len(python_course)
print(f"Number of students enrolled in Python course: {python_count}")
 
java_only_count = len(java_course - python_course)
print(f"Number of students enrolled only in Java course: {java_only_count}")
 
python_only_count= len(python_course - java_course)
print(f"Numbe of students enrolled only in Python course:{python_only_count}")
 
both_courses_count = len(java_course & python_course)
print(f"Number of students enrolled in both Java and Python courses: {both_courses_count}")
 
either_but_not_both_count = len((java_course - python_course) | (python_course - java_course))
print(f"Number of students enrolled in either Java or Python, but not both: {either_but_not_both_count}")
 
either_course_count = len(java_course | python_course)
print(f"Number of students enrolled in either Java or Python courses: {either_course_count}")


Number of students enrolled in Python course: 4
Number of students enrolled only in Java course: 2
Numbe of students enrolled only in Python course:2
Number of students enrolled in both Java and Python courses: 2
Number of students enrolled in either Java or Python, but not both: 4
Number of students enrolled in either Java or Python courses: 6


In [ ]:
import itertools

def get_permutations(digits):
    return [list(p) for p in itertools.permutations(digits)]

digits = [1, 2, 3]
result = get_permutations(digits)
print(result)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


In [ ]:
def outerFun(a, b):
    def innerFun(c, d):
        return c + d
    return innerFun(a, b)

res = outerFun(5, 10)
print(res)

15


In [ ]:
def largest_consecutive(num):
    num_set=set(num)
    print(num_set)
    max_length = 0
    
    for num in num_set:
        if num - 1 not in num_set:
            current_num = num
            current_length = 1
            while current_num +1 in num_set:
                current_num += 1
                current_length +=1
            max_length = max(max_length,current_length)
    return max_length

num=[100,4,200,1,3,2]
result= largest_consecutive(num)
print(result)

{1, 2, 3, 100, 4, 200}
4


In [ ]:
def add(a, b):
    return a+5, b+5

result = add(3, 2)
print(result)

(8, 7)


In [ ]:
def display(**kwargs):
    for i in kwargs:
        print(i)
display(emp="Kelly", salary=9000)


emp
salary
